# -*- coding: utf-8 -*-
"""untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/djakasatria2-beep/731bb19d7ed8f3337b1f593fad45ba4c/untitled2.ipynb
"""

!pip install google-play-scraper vaderSentiment deep-translator matplotlib

from google_play_scraper import reviews, Sort
import csv

result, _ = reviews(
    'com.bpjstku',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=200
)

df = pd.DataFrame(result)
df = df[['userName', 'score', 'at', 'content']]

df.to_csv('ulasan_jmo.csv', index=False)

print("Data berhasil diambil")
df.head()

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

model_name = "w11wo/indonesian-roberta-base-sentiment-classifier"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

label_map = {0: 'Positif', 1: 'Netral', 2: 'Negatif'}

def get_sentiment(text):
    if pd.isna(text):
        return 'Netral'

    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    predicted_class_id = torch.argmax(logits, dim=1).item()

    return label_map[predicted_class_id]

df['sentiment'] = df['content'].apply(get_sentiment)

df[['content', 'sentiment']].head()

import matplotlib.pyplot as plt

sentiment_counts = df['sentiment'].value_counts()

labels = sentiment_counts.index
values = sentiment_counts.values

colors = ['green', 'gray', 'red']

bars = plt.bar(labels, values, color=colors)

plt.title("Analisis Sentimen JMO Mobile (IndoBERT)")
plt.xlabel("Sentimen")
plt.ylabel("Jumlah")

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, int(yval),
             ha='center', va='bottom')

plt.show()